# =============================================================================
# GLAZEWM CONFIGURATION
# Optimized for dual monitor setup with workspace-specific application routing
# =============================================================================

# =============================================================================
# GENERAL SETTINGS
# =============================================================================
general:
  # Commands to run when the WM has started
  startup_commands:
    - "shell-exec yasb"
    # - "shell-exec altsnap"

  # Commands to run just before the WM is shutdown
  shutdown_commands:
    - "shell-exec taskkill /IM yasb.exe /F"

  # Commands to run after the WM config is reloaded
  config_reload_commands:
    - "shell-exec taskkill /IM yasb.exe /F"
    - "shell-exec yasb"
    - "wm-redraw"

  # Whether to automatically focus windows underneath the cursor (matching Komorebi's focus_follows_mouse)
  focus_follows_cursor: true

  # Whether to switch back and forth between the previously focused workspace
  toggle_workspace_on_refocus: true

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger (matching Komorebi's mouse_follows_focus)
    enabled: true
    # Trigger for cursor jump
    trigger: "window_focus"

# =============================================================================
# VISUAL APPEARANCE
# =============================================================================
gaps:
  # Whether to scale the gaps with the DPI of the monitor
  scale_with_dpi: true
  # Gap between adjacent windows (matching Komorebi's default_container_padding: 4)
  inner_gap: "4px"
  # Gap between windows and the screen edge (matching Komorebi's default_workspace_padding: 4)
  outer_gap:
    top: "4px"
    right: "4px"
    bottom: "4px"
    left: "4px"

window_effects:
  # Visual effects to apply to the focused window
  focused_window:
    # Highlight the window with a colored border
    border:
      enabled: true
      color: "#61afef"    # Blue accent color
      width: 1
    # Remove the title bar from the window's frame
    hide_title_bar:
      enabled: false
    # Change the corner style of the window's frame
    # ** Exclusive to Windows 11 due to API limitations
    corner_style:
      enabled: true
      style: "rounded"    # Options: "square", "rounded", "small_rounded"
    # Add transparency effects
    transparency:
      enabled: false
      opacity: 0.95

  # Visual effects to apply to non-focused windows
  other_windows:
    border:
      enabled: true
      color: "#3e4451"    # Dimmed border for unfocused windows
      width: 1
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: "rounded"
    transparency:
      enabled: true
      opacity: 0.99

# =============================================================================
# WINDOW BEHAVIOR
# Optimized for productivity workflow
# =============================================================================
window_behavior:
  # New windows are created in this state whenever possible
  # Allowed values: "tiling", "floating"
  initial_state: "tiling"

  # Sets the default options for when a new window is created
  state_defaults:
    floating:
      # Whether to center floating windows by default
      centered: true
      # Whether to show floating windows as always on top
      shown_on_top: false
    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead
      maximized: false
      # Whether to show fullscreen windows as always on top
      shown_on_top: false

# =============================================================================
# WORKSPACES
# Optimized for dual monitor productivity workflow
# =============================================================================
workspaces:
  # PRIMARY MONITOR (Monitor 0) - Core workflow
  - name: "1"
    display_name: "1.TERM"
    bind_to_monitor: 0
    keep_alive: true
  - name: "5"
    display_name: "5.FILES"
    bind_to_monitor: 0
    # keep_alive: true

  # SECONDARY MONITOR (Monitor 1) - Development & Browsing
  - name: "2"
    display_name: "2.CHROME"
    bind_to_monitor: 1
    keep_alive: true
  - name: "3"
    display_name: "3.DEV"
    bind_to_monitor: 1
    # keep_alive: true
  - name: "4"
    display_name: "4.WEB"
    bind_to_monitor: 1
    # keep_alive: true
  - name: "6"
    display_name: "6.MISC"
    bind_to_monitor: 1
    # No monitor binding - flexible placement
  - name: "7"
    display_name: "7.EXTRA"
  - name: "8"
    display_name: "8.EXTRA"
  - name: "9"
    display_name: "9.EXTRA"
  - name: "10"
    display_name: "10.EXTRA"

# Monitor Layout (matching Komorebi structure):
# Monitor 0 (Primary): Terminal (1.TERM), File Management (2.FILES)
# Monitor 1 (Secondary): Development (3.DEV), Chrome (4.CHROME), Web Browsing (5.WEB), Miscellaneous (6.MISC)

# =============================================================================
# WINDOW RULES
# Automatic application routing and window management based on new workspace layout
# =============================================================================
window_rules:
  # Terminal Applications → Workspace 1.TERM (Primary Monitor)
  - commands: ["move --workspace 1", "focus --workspace 1"]
    match:
      # Terminal applications
      - window_process: { regex: "WindowsTerminal|wezterm|cmd|powershell|pwsh" }
      - window_title: { regex: "Command Prompt|PowerShell|Terminal" }

  # File Management → Workspace 5.FILES (Primary Monitor)
  - commands: ["move --workspace 5", "focus --workspace 5"]
    match:
      # File managers and explorers
      - window_process: { regex: "dopus|explorer" }
      - window_title: { regex: "File Explorer|Directory Opus" }
      # Search tools
      - window_process: { equals: "everything" }

  # Chrome → Workspace 2.CHROME (Secondary Monitor)
  - commands: ["move --workspace 2", "focus --workspace 2"]
    match:
      # Chrome specifically
      - window_process: { equals: "chrome" }


  # Development Tools → Workspace 3.DEV (Secondary Monitor)
  - commands: ["move --workspace 3", "focus --workspace 3"]
    match:
      # Code editors and IDEs
      - window_process: { regex: "Code|devenv|Code - Insiders" }
      - window_title: { regex: "Visual Studio Code|Visual Studio 2022|.*\\.cs - Visual Studio|.*\\.ahk - Visual Studio Code" }
      # Database tools
      - window_process: { regex: "dbforge.*?" }

  # Web Browsers → Workspace 5.WEB (Secondary Monitor)
  - commands: ["move --workspace 4", "focus --workspace 4"]
    match:
      # Firefox and Edge for web browsing
      - window_process: { regex: "firefox|msedge" }

  # Communication & Office → Workspace 6.MISC (Flexible)
  - commands: ["move --workspace 6", "focus --workspace 6"]
    match:
      # Communication apps
      - window_process: { regex: "ms-teams|slack|discord|Mailbird|telegram|whatsapp" }
      # Office applications
      - window_process: { regex: "WINWORD|EXCEL|MSPUB|MSACCESS|soffice|wordpad" }
      # Other browsers
      - window_process: { regex: "brave|opera|vivaldi" }

  # Floating Applications (matching Komorebi floating_applications)
  - commands: ["set-floating --centered"]
    match:
      # Text editors and utilities
      - window_process: { regex: "sublime_text|TreeSize|PotPlayerMini64|QuranWindows|quran-companion" }
      # Launcher and search utilities
      - window_process: { regex: "everything|launchy|keypirinha|executor" }
      # System utilities
      - window_process: { regex: "Taskmgr|ProcessHacker|winspy|Calculator|notepad|mspaint" }
      - window_process: { equals: "DeepL" }
      # Productivity tools
      - window_process: { regex: "ShareX|snippet-tool|ColorPicker" }
      # Communication (Slack floating like Komorebi)
      - window_process: { equals: "slack" }

  # System & Utility Apps (Ignored - matching Komorebi ignore_rules)
  - commands: ["ignore"]
    match:
      # Status bars and system utilities
      - window_process: { regex: "yasb|zebar|Flow.Launcher|AltSnap" }
      - window_process: { regex: "Taskmgr|ScreenClippingHost" }
      - window_process: { regex: "voicemeeterpro|voicemeeter8x64" }
      # PowerToys applications
      - window_process: { regex: "PowerToys" }
      - window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }

      # Dialog boxes and system windows
      - window_title: { regex: "Save As|Open|Print|Find|Replace" }
      - window_title: { regex: "Properties|Settings|Preferences|Options" }
      - window_title: { regex: "About|Help|Error|Warning|Confirmation|dialog|alert" }
      - window_title: { regex: "Update|Install|Authentication|Login|Password" }
      - window_class: { regex: "#32768|#32769|#32770" }
      - window_class: { regex: "CabinetWClass|TaskManagerWindow|ApplicationFrameWindow" }

      # Browser picture-in-picture
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }

      # Application-specific ignore rules
      - window_title: { equals: "TODO Tasks" }
      - window_process: { regex: "AutoHotkey.*?" }
      - window_process: { regex: "POPsRestaurant|pops_enterprise|Retail.Main.BackOffice|Retail.Main.POS" }
      - window_title: { regex: "Swagger UI.*?" }

# =============================================================================
# BINDING MODES
# Special input modes for enhanced control
# =============================================================================
binding_modes:
  # Resize mode: Use HJKL or arrow keys to resize windows
  - name: "resize"
    keybindings:
      - commands: ["resize --width -2%"]
        bindings: ["h", "right"]
      - commands: ["resize --width +2%"]
        bindings: ["l", "left"]
      - commands: ["resize --height +2%"]
        bindings: ["k", "up"]
      - commands: ["resize --height -2%"]
        bindings: ["j", "down"]
      # Exit resize mode
      - commands: ["wm-disable-binding-mode --name resize"]
        bindings: ["escape", "enter"]

  # Pause mode: Disable all keybindings temporarily
  - name: "pause"
    keybindings:
      - commands: ["wm-disable-binding-mode --name pause"]
        bindings: ["alt+shift+z"]

# =============================================================================
# KEYBINDINGS
# Main keyboard shortcuts for window management
# =============================================================================
keybindings:
  # System Controls
  - commands: ["wm-enable-binding-mode --name resize"]
    bindings: ["alt+shift+r"]
  - commands: ["wm-enable-binding-mode --name pause"]
    bindings: ["alt+shift+z"]
  - commands: ["wm-exit"]
    bindings: ["alt+ctrl+shift+k"]
  - commands: ["wm-reload-config"]
    bindings: ["alt+ctrl+lwin+q"]
  - commands: ["wm-redraw"]
    bindings: ["alt+ctrl+lwin+w"]

  # Application Launcher
  - commands: ["shell-exec wezterm-gui"]
    bindings: ["alt+enter"]

  # Window State Controls
  - commands: ["toggle-tiling-direction"]
    bindings: ["alt+shift+v"]
  - commands: ["toggle-floating --centered"]
    bindings: ["alt+shift+z"]
  - commands: ["toggle-tiling"]
    bindings: ["alt+ctrl+t"]
  - commands: ["toggle-fullscreen"]
    bindings: ["alt+shift+f"]
  - commands: ["toggle-minimized"]
    bindings: ["alt+ctrl+m"]
  - commands: ["close"]
    bindings: ["alt+shift+c"]

  # Layout Management (matching Komorebi layout commands)
  # - commands: ["set-tiling-direction --direction vertical"]
  #   bindings: ["alt+shift+s"]
  # - commands: ["set-tiling-direction --direction horizontal"]
  #   bindings: ["alt+shift+h"]

  # Window Focus Navigation (HJKL + Arrow Keys - matching Komorebi)
  - commands: ["focus --direction left"]
    bindings: ["alt+ctrl+h", "alt+ctrl+left"]
  - commands: ["focus --direction right"]
    bindings: ["alt+ctrl+l", "alt+ctrl+right"]
  - commands: ["focus --direction up"]
    bindings: ["alt+ctrl+k", "alt+ctrl+up"]
  - commands: ["focus --direction down"]
    bindings: ["alt+ctrl+j", "alt+ctrl+down"]

  # Window Movement (HJKL + Arrow Keys - matching Komorebi)
  - commands: ["move --direction left"]
    bindings: ["alt+shift+h", "alt+shift+left"]
  - commands: ["move --direction right"]
    bindings: ["alt+shift+l", "alt+shift+right"]
  - commands: ["move --direction up"]
    bindings: ["alt+shift+k", "alt+shift+up"]
  - commands: ["move --direction down"]
    bindings: ["alt+shift+j", "alt+shift+down"]

  # Window Resizing (enhanced like Komorebi)
  - commands: ["resize --width +2%"]
    bindings: ["alt+ctrl+lwin+l", "alt+ctrl+lwin+right"]
  - commands: ["resize --width -2%"]
    bindings: ["alt+ctrl+lwin+h", "alt+ctrl+lwin+left"]
  - commands: ["resize --height +2%"]
    bindings: ["alt+ctrl+lwin+k", "alt+ctrl+lwin+up"]
  - commands: ["resize --height -2%"]
    bindings: ["alt+ctrl+lwin+j", "alt+ctrl+lwin+down"]

  # Workspace Focus (1-6 matching Komorebi workspace names)
  - commands: ["focus --workspace 1"]
    bindings: ["alt+1"]
  - commands: ["focus --workspace 2"]
    bindings: ["alt+2"]
  - commands: ["focus --workspace 3"]
    bindings: ["alt+3"]
  - commands: ["focus --workspace 4"]
    bindings: ["alt+4"]
  - commands: ["focus --workspace 5"]
    bindings: ["alt+5"]
  - commands: ["focus --workspace 6"]
    bindings: ["alt+6"]
  - commands: ["focus --workspace 7"]
    bindings: ["alt+7"]
  - commands: ["focus --workspace 8"]
    bindings: ["alt+8"]
  - commands: ["focus --workspace 9"]
    bindings: ["alt+9"]
  - commands: ["focus --workspace 10"]
    bindings: ["alt+0"]

  # Move Window to Workspace (matching Komorebi behavior)
  - commands: ["move --workspace 1", "focus --workspace 1"]
    bindings: ["alt+shift+1"]
  - commands: ["move --workspace 2", "focus --workspace 2"]
    bindings: ["alt+shift+2"]
  - commands: ["move --workspace 3", "focus --workspace 3"]
    bindings: ["alt+shift+3"]
  - commands: ["move --workspace 4", "focus --workspace 4"]
    bindings: ["alt+shift+4"]
  - commands: ["move --workspace 5", "focus --workspace 5"]
    bindings: ["alt+shift+5"]
  - commands: ["move --workspace 6", "focus --workspace 6"]
    bindings: ["alt+shift+6"]
  - commands: ["move --workspace 7", "focus --workspace 7"]
    bindings: ["alt+shift+7"]
  - commands: ["move --workspace 8", "focus --workspace 8"]
    bindings: ["alt+shift+8"]
  - commands: ["move --workspace 9", "focus --workspace 9"]
    bindings: ["alt+shift+9"]
  - commands: ["move --workspace 10", "focus --workspace 10"]
    bindings: ["alt+shift+0"]

  # Workspace Navigation (matching Komorebi CycleWorkspace)
  - commands: ["focus --next-workspace"]
    bindings: ["alt+tab"]
  - commands: ["focus --prev-workspace"]
    bindings: ["alt+shift+tab"]
  - commands: ["focus --recent-workspace"]
    bindings: ["alt+d"]

  # Move Workspace Between Monitors
  - commands: ["move-workspace --direction left"]
    bindings: ["alt+ctrl+shift+left"]
  - commands: ["move-workspace --direction right"]
    bindings: ["alt+ctrl+shift+right"]
  - commands: ["move-workspace --direction up"]
    bindings: ["alt+ctrl+shift+up"]
  - commands: ["move-workspace --direction down"]
    bindings: ["alt+ctrl+shift+down"]
