# =============================================================================
# GLAZEWM CONFIGURATION
# Optimized for dual monitor setup with workspace-specific application routing
# =============================================================================

# =============================================================================
# GENERAL SETTINGS
# =============================================================================
general:
  # Commands to run when the WM has started
  startup_commands:
    - "shell-exec zebar"
    - "shell-exec altsnap"

  # Commands to run just before the WM is shutdown
  shutdown_commands:
    - "shell-exec taskkill /IM zebar.exe /F"

  # Commands to run after the WM config is reloaded
  config_reload_commands:
    - "shell-exec taskkill /IM zebar.exe /F"
    - "shell-exec zebar"
    - "wm-redraw"

  # Whether to automatically focus windows underneath the cursor
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace
  toggle_workspace_on_refocus: true

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger
    enabled: true

    # Trigger for cursor jump:
    # - "monitor_focus": Jump when focus changes between monitors.
    # - "window_focus": Jump when focus changes between windows.
    trigger: "window_focus"

# =============================================================================
# VISUAL APPEARANCE
# =============================================================================
gaps:
  # Whether to scale the gaps with the DPI of the monitor
  scale_with_dpi: true
  # Gap between adjacent windows
  inner_gap: "8px"
  # Gap between windows and the screen edge
  outer_gap:
    top: "40px"    # Extra space for status bar
    right: "8px"
    bottom: "8px"
    left: "8px"

window_effects:
  # Visual effects to apply to the focused window
  focused_window:
    # Highlight the window with a colored border
    border:
      enabled: true
      color: "#61afef"    # Blue accent color
      width: 2
    # Remove the title bar from the window's frame
    hide_title_bar:
      enabled: false
    # Change the corner style of the window's frame
    # ** Exclusive to Windows 11 due to API limitations
    corner_style:
      enabled: true
      style: "rounded"    # Options: "square", "rounded", "small_rounded"
    # Add transparency effects
    transparency:
      enabled: false
      opacity: 0.95

  # Visual effects to apply to non-focused windows
  other_windows:
    border:
      enabled: true
      color: "#3e4451"    # Dimmed border for unfocused windows
      width: 1
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: "rounded"
    transparency:
      enabled: false
      opacity: 0.90

# =============================================================================
# WINDOW BEHAVIOR
# =============================================================================
window_behavior:
  # New windows are created in this state whenever possible
  # Allowed values: "tiling", "floating"
  initial_state: "tiling"

  # Sets the default options for when a new window is created
  state_defaults:
    floating:
      # Whether to center floating windows by default
      centered: true
      # Whether to show floating windows as always on top
      shown_on_top: false
    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead
      maximized: true
      # Whether to show fullscreen windows as always on top
      shown_on_top: false

# =============================================================================
# WORKSPACES
# Configured for dual monitor setup
# =============================================================================
workspaces:
  - name: "1"
    display_name: "1: 󰋜 HOME"
    bind_to_monitor: 0
    keep_alive: true
  - name: "2"
    # display_name: "2:   DEV"
    display_name: "2:  ‎ DEV"
    bind_to_monitor: 1
    keep_alive: true
  - name: "3"
    display_name: "3: 󰈹 WEB"
    bind_to_monitor: 1
  - name: "4"
    display_name: "4:  OTHERS"
    # bind_to_monitor: 0
  - name: "5"
    display_name: "5:  TEST"
  - name: "6"
    display_name: "6:      "
  - name: "7"
    display_name: "7:      "
  - name: "8"
    display_name: "8:      "
  - name: "9"
    display_name: "9:     "
  - name: "10"
    display_name: "10:     "

# My Configuration: 2 physical displays/monitors
# - Monitor 0: Primary (left) - Workspace 1kkk

# =============================================================================
# WINDOW RULES
# Automatic application routing and window management
# =============================================================================
window_rules:
  # Communication & Office Apps → Workspace 1 (Primary Monitor)
  - commands: ["move --workspace 1", "focus --workspace 1", "set-fullscreen"]
    match:
      # Communication apps
      - window_process: { regex: "ms-teams|slack|discord|Mailbird|telegram|whatsapp" }
      # Microsoft Office and document editors
      - window_process: { regex: "WINWORD|EXCEL|MSPUB|MSACCESS|soffice|wordpad" }
      # File managers
      - window_process: { regex: "dopus|explorer" }

  # Development Tools → Workspace 2 (Secondary Monitor)
  - commands: ["move --workspace 2", "focus --workspace 2", "set-fullscreen", "wm-redraw"]
    match:
      # Code editors and IDEs
      - window_process: { regex: "Code - Insiders|Code|dbforge.*?|devenv" }

  # Web Browsers → Workspace 3 (Secondary Monitor)
  - commands: ["move --workspace 3", "focus --workspace 3", "set-fullscreen"]
    match:
      # All major browsers
      - window_process: { regex: "chrome|firefox|brave|opera|vivaldi" }

  # System & Utility Apps (Ignored - Don't manage these windows)
  - commands: ["ignore"]
    match:
      # System and utility apps that should not be managed
      - window_process: { regex: "zebar|Flow.Launche|AltSnap" }
      - window_process: { regex: "Taskmgr|ScreenClippingHost" }
      - window_process: { regex: "voicemeeterpro|voicemeeter8x64" }
      # Common dialog boxes
      - window_title: { regex: "Save As|Open|Print|Find|Replace" }
      - window_class: { regex: "#32768|#32769" }
      - window_class: { equals: "#32770" }
      - window_title: { regex: ".*?dialog.*?|.*?alert.*?" }
      # Settings and properties dialogs
      - window_title: { regex: ".*?Properties|.*?Settings|.*?Preferences|.*?Options" }
      # Windows with question marks (dialogs, prompts, confirmations)
      - window_title: { regex: ".*\\?.*" }

      # Browser picture-in-picture windows
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }

      # PowerToys applications
      - window_process: { equals: "PowerToys" }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: "PowerToys" }
        window_title: { regex: ".*? - Peek" }
        window_class: { regex: "HwndWrapper" }

      # Application-specific ignore rules
      - window_title: { equals: "TODO Tasks" }
      - window_process: { regex: "AutoHotkey.*?" }
      - window_process: { regex: "POPsRestaurant|pops_enterprise|Retail.Main.BackOffice|Retail.Main.POS" }
      - window_title: { regex: "Swagger UI.*?" }
      - window_title: { equals: "ShareX - Image editor" }

  # Floating Windows (Not tiled, but still managed)
  - commands: ["set-floating"]
    match:
      # Text editors and media players
      - window_process: { regex: "sublime_text|TreeSize|PotPlayerMini64|QuranWindows|quran-companion" }
      # Search and launcher utilities
      - window_process: { regex: "everything|launchy|keypirinha|executor" }

  # Centered Floating Windows (Special positioning)
  - commands: ["set-floating --centered"]
    match:
      # System utilities and small applications
      - window_process: { regex: "Taskmgr|ProcessHacker|winspy|Calculator|notepad|mspaint|WindowsTerminal|ApplicationFrameHost" }
      - window_title: { regex: "Volume Mixer|Settings|Task Manager" }
      - window_process: { equals: "DeepL" }

  # Fullscreen Windows (Force fullscreen for specific applications)
  - commands: ["set-fullscreen"]
    match:
      - window_title: { regex: "ShareX - Image editor - .*?" }

# =============================================================================
# BINDING MODES
# Special input modes for enhanced control
# =============================================================================
binding_modes:
  # Resize mode: Use HJKL or arrow keys to resize windows
  - name: "resize"
    keybindings:
      - commands: ["resize --width -2%"]
        bindings: ["h", "right"]
      - commands: ["resize --width +2%"]
        bindings: ["l", "left"]
      - commands: ["resize --height +2%"]
        bindings: ["k", "up"]
      - commands: ["resize --height -2%"]
        bindings: ["j", "down"]
      # Exit resize mode
      - commands: ["wm-disable-binding-mode --name resize"]
        bindings: ["escape", "enter"]

  # Pause mode: Disable all keybindings temporarily
  - name: "pause"
    keybindings:
      - commands: ["wm-disable-binding-mode --name pause"]
        bindings: ["alt+shift+z"]

# =============================================================================
# KEYBINDINGS
# Main keyboard shortcuts for window management
# =============================================================================
keybindings:
  # System Controls
  - commands: ["wm-enable-binding-mode --name resize"]
    bindings: ["alt+shift+r"]
  - commands: ["wm-enable-binding-mode --name pause"]
    bindings: ["alt+shift+z"]
  - commands: ["wm-exit"]
    bindings: ["alt+ctrl+shift+k"]
  - commands: ["wm-reload-config"]
    bindings: ["alt+ctrl+lwin+q"]
  - commands: ["wm-redraw"]
    bindings: ["alt+ctrl+lwin+w"]

  # Application Launcher
  - commands: ["shell-exec wezterm-gui"]
    bindings: ["alt+enter"]

  # Window State Controls
  - commands: ["toggle-tiling-direction"]
    bindings: ["alt+shift+v"]
  - commands: ["toggle-floating --centered"]
    bindings: ["alt+ctrl+f"]
  - commands: ["toggle-tiling"]
    bindings: ["alt+ctrl+t"]
  - commands: ["toggle-fullscreen"]
    bindings: ["alt+shift+f"]
  - commands: ["toggle-minimized"]
    bindings: ["alt+ctrl+m"]
  - commands: ["close"]
    bindings: ["alt+shift+c"]

  # Window Focus Navigation (HJKL + Arrow Keys)
  - commands: ["focus --direction left"]
    bindings: ["alt+ctrl+h", "alt+ctrl+left"]
  - commands: ["focus --direction right"]
    bindings: ["alt+ctrl+l", "alt+ctrl+right"]
  - commands: ["focus --direction up"]
    bindings: ["alt+ctrl+k", "alt+ctrl+up"]
  - commands: ["focus --direction down"]
    bindings: ["alt+ctrl+j", "alt+ctrl+down"]

  # Window Movement (HJKL + Arrow Keys)
  - commands: ["move --direction left"]
    bindings: ["alt+shift+h", "alt+shift+left"]
  - commands: ["move --direction right"]
    bindings: ["alt+shift+l", "alt+shift+right"]
  - commands: ["move --direction up"]
    bindings: ["alt+shift+k", "alt+shift+up"]
  - commands: ["move --direction down"]
    bindings: ["alt+shift+j", "alt+shift+down"]

  # Window Resizing (HJKL + Arrow Keys)
  - commands: ["resize --width +2%"]
    bindings: ["alt+ctrl+lwin+h", "alt+ctrl+left"]
  - commands: ["resize --width -2%"]
    bindings: ["alt+ctrl+lwin+l", "alt+ctrl+right"]
  - commands: ["resize --height +2%"]
    bindings: ["alt+ctrl+lwin+k", "alt+ctrl+up"]
  - commands: ["resize --height -2%"]
    bindings: ["alt+ctrl+lwin+j", "alt+ctrl+down"]

  # Workspace Focus (Number Keys 1-5)
  - commands: ["focus --workspace 1"]
    bindings: ["alt+1"]
  - commands: ["focus --workspace 2"]
    bindings: ["alt+2"]
  - commands: ["focus --workspace 3"]
    bindings: ["alt+3"]
  - commands: ["focus --workspace 4"]
    bindings: ["alt+4"]
  - commands: ["focus --workspace 5"]
    bindings: ["alt+5"]
  - commands: ["focus --workspace 6"]
    bindings: ["alt+6"]
  - commands: ["focus --workspace 7"]
    bindings: ["alt+7"]
  - commands: ["focus --workspace 8"]
    bindings: ["alt+8"]
  - commands: ["focus --workspace 9"]
    bindings: ["alt+9"]
  - commands: ["focus --workspace 10"]
    bindings: ["alt+0"]


  # Move Window to Workspace (Shift + Number Keys)
  - commands: ["move --workspace 1", "focus --workspace 1"]
    bindings: ["alt+shift+1"]
  - commands: ["move --workspace 2", "focus --workspace 2"]
    bindings: ["alt+shift+2"]
  - commands: ["move --workspace 3", "focus --workspace 3"]
    bindings: ["alt+shift+3"]
  - commands: ["move --workspace 4", "focus --workspace 4"]
    bindings: ["alt+shift+4"]
  - commands: ["move --workspace 5", "focus --workspace 5"]
    bindings: ["alt+shift+5"]
  - commands: ["move --workspace 6", "focus --workspace 6"]
    bindings: ["alt+shift+6"]
  - commands: ["move --workspace 7", "focus --workspace 7"]
    bindings: ["alt+shift+7"]
  - commands: ["move --workspace 8", "focus --workspace 8"]
    bindings: ["alt+shift+8"]
  - commands: ["move --workspace 9", "focus --workspace 9"]
    bindings: ["alt+shift+9"]
  - commands: ["move --workspace 10", "focus --workspace 10"]
    bindings: ["alt+shift+0"]

  # Workspace Navigation (Quick switching)
  - commands: ["focus --next-workspace"]
    bindings: ["alt+s"]
  - commands: ["focus --prev-workspace"]
    bindings: ["alt+a"]
  - commands: ["focus --recent-workspace"]
    bindings: ["alt+d"]

  # Move Workspace Between Monitors
  - commands: ["move-workspace --direction left"]
    bindings: ["alt+ctrl+shift+left"]
  - commands: ["move-workspace --direction right"]
    bindings: ["alt+ctrl+shift+right"]
  - commands: ["move-workspace --direction up"]
    bindings: ["alt+ctrl+shift+up"]
  - commands: ["move-workspace --direction down"]
    bindings: ["alt+ctrl+shift+down"]
